// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart'
    show Firebase, FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'firebase_options.dart';

Future<void> initializeFirebase() async {
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
}

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoncF4OaPlNQIMKHll1MoHQyWYta0ex8E',
    appId: '1:29923146751:web:11df97dd1ff363f83f45ca',
    messagingSenderId: '29923146751',
    projectId: 'taxi-app-2f01a',
    authDomain: 'taxi-app-2f01a.firebaseapp.com',
    storageBucket: 'taxi-app-2f01a.appspot.com',
    measurementId: 'G-7GKDJM1QFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqhtrf77P2ZZeaCfQqP0vWQf7zIBLgDRo',
    appId: '1:29923146751:android:184e47d54233b4013f45ca',
    messagingSenderId: '29923146751',
    projectId: 'taxi-app-2f01a',
    storageBucket: 'taxi-app-2f01a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp0fLwKj9HXGEin8i3fh74NFrQcFOOnSo',
    appId: '1:29923146751:ios:c64f87881f29f4c93f45ca',
    messagingSenderId: '29923146751',
    projectId: 'taxi-app-2f01a',
    storageBucket: 'taxi-app-2f01a.appspot.com',
    iosBundleId: 'com.example.taxi1App',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp0fLwKj9HXGEin8i3fh74NFrQcFOOnSo',
    appId: '1:29923146751:ios:c64f87881f29f4c93f45ca',
    messagingSenderId: '29923146751',
    projectId: 'taxi-app-2f01a',
    storageBucket: 'taxi-app-2f01a.appspot.com',
    iosBundleId: 'com.example.taxi1App',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoncF4OaPlNQIMKHll1MoHQyWYta0ex8E',
    appId: '1:29923146751:web:dd32e0994a0c4b413f45ca',
    messagingSenderId: '29923146751',
    projectId: 'taxi-app-2f01a',
    authDomain: 'taxi-app-2f01a.firebaseapp.com',
    storageBucket: 'taxi-app-2f01a.appspot.com',
    measurementId: 'G-29T6X0RV3N',
  );
}
